Repository Puh00/Bookly, pull requests merged in 2020-08, with the labels that each got.

#7 Puh branch
  app/build.gradle
  app/src/main/java/com/example/bookly/AddABookFragment.kt
  app/src/main/java/com/example/bookly/MyProfileFragment.kt
  app/src/main/java/com/example/bookly/backend/BooklyDataHandler.java
  app/src/main/java/com/example/bookly/backend/User.java
  app/src/main/res/drawable/default_profile_picture.png
  app/src/main/res/layout/fragment_add_a_book.xml
  app/src/main/res/layout/fragment_my_profile.xml
Labels: enhancement

#8 fragment_write_a_review.xml & WriteAReviewFragment.kt
  app/src/main/java/com/example/bookly/AddABookFragment.kt
  app/src/main/java/com/example/bookly/WriteAReviewFragment.kt
  app/src/main/java/com/example/bookly/backend/BooklyDataHandler.java
  app/src/main/java/com/example/bookly/backend/Review.java
  app/src/main/res/layout/fragment_write_a_review.xml
Labels: enhancement

#13 Kusu
  app/src/main/java/com/example/bookly/MainActivity.kt
  app/src/main/java/com/example/bookly/MyBooksFragment.kt
  app/src/main/java/com/example/bookly/backend/BooklyDataHandler.java
  app/src/main/java/com/example/bookly/backend/IOHandler.java
Labels: enhancement

#23 refactored the iohandling code sligtly and fixed issue #22
  app/src/main/java/com/example/bookly/backend/BooklyDataHandler.java
  app/src/main/java/com/example/bookly/backend/IOHandler.java
Labels: bug

#25 updated MyProfileFragment's appearance and fixed a problem where prof…
  app/src/main/java/com/example/bookly/MainActivity.kt
  app/src/main/java/com/example/bookly/MyProfileFragment.kt
  app/src/main/java/com/example/bookly/backend/BooklyDataHandler.java
  app/src/main/java/com/example/bookly/backend/User.java
  app/src/main/res/drawable/stack_of_books.png
  app/src/main/res/layout/fragment_my_profile.xml
Labels: bug, enhancement
